[target.aarch64-linux-android]
image = "contrasleuth-docker-support/cross-utils:aarch64-linux-android"
[target.arm-linux-androideabi]
image = "contrasleuth-docker-support/cross-utils:arm-linux-androideabi"
[target.armv7-linux-androideabi]
image = "contrasleuth-docker-support/cross-utils:armv7-linux-androideabi"
[target.i686-linux-android]
image = "contrasleuth-docker-support/cross-utils:i686-linux-android"
[target.x86_64-linux-android]
image = "contrasleuth-docker-support/cross-utils:x86_64-linux-android"
